enum_discrim_align_threshold = 20
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
inline_attribute_width = 50
max_width = 120
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 20
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
