[package]
name = "derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
macro = { version = "0.1.0", path = "../macro" }
proc-macro2 = "1.0.50"
quote = "1.0.23"
syn = "1.0.107"
